repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.3  # Use the latest stable version or the specific version you need
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--use-standard-markers=true
