---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.15.0
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: elasticsearch
    logs:
      elasticsearchRefs:
      - name: elasticsearch
  nodeSets:
  - name: main
    count: 1
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        volumes:
        - name: elasticsearch-data
          emptyDir: {}
    config:
      xpack.security.audit.enabled: false
      xpack.security.enrollment.enabled: false
      node.store.allow_mmap: false
      xpack.security.transport.ssl.verification_mode: 'none'
      
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  auth:
    disableElasticUser: true
    fileRealm:
    - secretName: elastic-credentials